// frontend/src/components/LangToggle.tsx
"use client";

import { useLocale } from "next-intl";
import { usePathname, useRouter } from "@/i18n/navigation";

export function LangToggle() {
  const locale = useLocale();
  const pathname = usePathname();
  const router = useRouter();

  function switchTo(next: "en" | "zh") {
    router.replace(pathname, { locale: next });
  }

  return (
    <div className="neo-surface inline-flex h-10 items-center rounded-full p-1 text-sm">
      <button
        type="button"
        onClick={() => switchTo("en")}
        className={`rounded-full px-3.5 py-1.5 font-medium transition duration-180 ${
          locale === "en"
            ? "bg-[#f3f6ff] text-brand shadow-[inset_1px_1px_3px_rgba(37,99,235,0.08)]"
            : "text-muted hover:text-foreground"
        }`}
      >
        EN
      </button>
      <button
        type="button"
        onClick={() => switchTo("zh")}
        className={`rounded-full px-3.5 py-1.5 font-medium transition duration-180 ${
          locale === "zh"
            ? "bg-[#f3f6ff] text-brand shadow-[inset_1px_1px_3px_rgba(37,99,235,0.08)]"
            : "text-muted hover:text-foreground"
        }`}
      >
        中文
      </button>
    </div>
  );
}

// backoffice/src/components/LangToggle.vue
<script setup>
import { useI18n } from "@/composables/useI18n";
import { cn } from "@/lib/utils";

const { locale, setLocale } = useI18n();
</script>

<template>
  <div
    class="inline-flex h-7 items-center rounded-md border border-neutral-200 bg-neutral-50 p-0.5"
  >
    <button
      type="button"
      :class="
        cn(
          'rounded px-2 text-xs font-medium transition-colors',
          locale === 'en'
            ? 'bg-white text-neutral-900 shadow-sm'
            : 'text-neutral-500 hover:text-neutral-900',
        )
      "
      @click="setLocale('en')"
    >
      EN
    </button>
    <button
      type="button"
      :class="
        cn(
          'rounded px-2 text-xs font-medium transition-colors',
          locale === 'zh'
            ? 'bg-white text-neutral-900 shadow-sm'
            : 'text-neutral-500 hover:text-neutral-900',
        )
      "
      @click="setLocale('zh')"
    >
      中文
    </button>
  </div>
</template>
